# Generated by Django 6.0.2 on 2026-02-26 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('image_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('published_at', models.DateTimeField()),
                ('ai_summary', models.TextField(blank=True, help_text='AI generated summary', null=True)),
                ('tags', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='categories.category')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
